image: debian/testing
packages:
- clang
- curl
- libx11-dev
- libx11-xcb-dev
- libxcb1-dev
- libxkbcommon-dev
- pkg-config
sources:
- https://git.sr.ht/~notgull/piet-hardware
secrets:
- 424251f4-3b9e-4f8b-8361-e000fe6222f3
tasks:
- install_rust:
    curl https://sh.rustup.rs -sSf | sh -s -- -y
- test: |
    cd piet-hardware
    sh ci/ci.sh 
- mirror: |
    cd piet-hardware
    ssh-keyscan -H -t rsa github.com  >> ~/.ssh/known_hosts
    git remote add github_origin git@github.com:notgull/piet-hardware.git
    git push github_origin main